import { UserRole } from '@/types';

export const roleCopy = {
  engineer: {
    // Console (Home)
    consoleTitle: "The Orchestrator's Console",
    consoleSearch: "type:project tags:auth metrics.forks>100",
    audit: "Audit",
    fork: "Fork",
    forked: "Forked",
    // Network
    networkSection: "System.Network",
    networkTitle: "Global Nodes",
    networkCount: "Active Orchestrators",
    networkAction: "Ping Node",
    networkMetric1: "Broadcasts",
    networkMetric2: "Fork Rate",
    // Identity
    identityMetric1Label: "Global Fork Rate",
    identityMetric1Value: "842",
    identityMetric1Icon: "⑂",
    identityMetric2Label: "Nodes Broadcasted",
    identityMetric2Value: "12",
    identityMetric3Label: "Peer Audits",
    identityMetric3Value: "56",
    identityMetric3Icon: "[A]",
    identityAction: "Initialize New Node",
    identityActionDesc: "Broadcast architectural logic to the network",
    // Init
    initSection: "System.Execute",
    initHeading: "Initialize Node",
    initBroadcast: "Broadcast to Console",
  },
  builder: {
    consoleTitle: "The Builder's Dashboard",
    consoleSearch: "Search apps, categories, or metrics...",
    audit: "Optimize",
    fork: "Clone",
    forked: "Cloned",
    networkSection: "Builder.Community",
    networkTitle: "Top Creators",
    networkCount: "Builders Online",
    networkAction: "Message",
    networkMetric1: "Apps",
    networkMetric2: "Install Rate",
    identityMetric1Label: "Total App Installs",
    identityMetric1Value: "12.4k",
    identityMetric1Icon: "⤓",
    identityMetric2Label: "Apps Published",
    identityMetric2Value: "4",
    identityMetric3Label: "Revenue Share",
    identityMetric3Value: "0.85",
    identityMetric3Icon: "$",
    identityAction: "Publish New App",
    identityActionDesc: "Launch your orchestrator to the global community",
    initSection: "Builder.Publish",
    initHeading: "Publish App",
    initBroadcast: "Publish to Network",
  },
  guest: {
    consoleTitle: "Explore Craftly Internet",
    consoleSearch: "Search by need (e.g., 'minimal portfolio')...",
    audit: "Rate",
    fork: "Save",
    forked: "Saved",
    networkSection: "Explore.People",
    networkTitle: "Global Community",
    networkCount: "People Exploring",
    networkAction: "Connect",
    networkMetric1: "Posts",
    networkMetric2: "Impact",
    identityMetric1Label: "Discovery Points",
    identityMetric1Value: "450",
    identityMetric1Icon: "☼",
    identityMetric2Label: "Nodes Saved",
    identityMetric2Value: "28",
    identityMetric3Label: "Contributions",
    identityMetric3Value: "12",
    identityMetric3Icon: "◈",
    identityAction: "Join a Network",
    identityActionDesc: "Connect with other digital orchestrators",
    initSection: "System.Execute",
    initHeading: "Initialize Node",
    initBroadcast: "Broadcast to Console",
  },
} as const satisfies Record<UserRole, Record<string, string>>;

export function getRoleCopy(role: UserRole) {
  return roleCopy[role];
}
