import { UserRole } from '@/types';

export const roleCopy = {
  engineer: {
    // Console (Home)
    home: "Console",
    consoleTitle: "The Orchestrator's Console",
    consoleSearch: "type:project tags:auth metrics.forks>100",
    audit: "Audit",
    fork: "Fork",
    forked: "Forked",
    // Network
    networkSection: "System.Network",
    networkTitle: "Global Nodes",
    networkCount: "Active Orchestrators",
    networkAction: "Ping Node",
    networkMetric1: "Broadcasts",
    networkMetric2: "Fork Rate",
    // Identity
    identityMetric1Label: "Global Fork Rate",
    identityMetric1Value: "842",
    identityMetric1Icon: "⑂",
    identityMetric2Label: "Nodes Broadcasted",
    identityMetric2Value: "12",
    identityMetric3Label: "Peer Audits",
    identityMetric3Value: "56",
    identityMetric3Icon: "[A]",
    identityAction: "Initialize New Node",
    identityActionDesc: "Broadcast architectural logic to the network",
    // Init
    initSection: "System.Execute",
    initHeading: "Initialize Node",
    initBroadcast: "Broadcast to Console",
    // Workbench
    workbench: "Workbench",
    workbenchUnauthorized: "The private sector is restricted to registered Orchestrators. You must initialize an identity to establish a Workbench and fork logic from the network.",
    workbenchUnauthorizedHeading: "[SYSTEM ERROR] UNREGISTERED NODE",
    toasts: {
      unauthorized: "[SYSTEM ERROR] UNAUTHORIZED. INITIALIZE IDENTITY.",
      identityInitialized: "[SYSTEM] IDENTITY INITIALIZED",
      broadcastSuccess: "[CONSOLE] NODE SUCCESSFULLY BROADCASTED",
      broadcastError: "[ERROR] UNAUTHORIZED. CANNOT BROADCAST.",
      networkPing: "[NETWORK] NODE PINGED: {name}",
      networkPingAll: "[NETWORK] PINGING ALL ACTIVE NODES...",
      workbenchSave: "[WORKBENCH] NODE FORKED AND SAVED",
      workbenchIntegrate: "[WORKBENCH] INITIATING INTEGRATION PROTOCOL",
      auditComplete: "[SYSTEM] AUDIT COMPLETE FOR NODE {name}",
      logout: "[SYSTEM] CONNECTION TERMINATED",
      loadingState: "Initializing Console...",
      errorBoundary: "[SYSTEM ERROR] RUNTIME FAULT",
      errorRetry: "Retry Connection",
      postDetail: "Developer Log // {id}",
      themeInverted: "[SYSTEM] THEME INVERTED",
    },
  },
  builder: {
    home: "Dashboard",
    consoleTitle: "The Builder's Dashboard",
    consoleSearch: "Search apps, categories, or metrics...",
    audit: "Optimize",
    fork: "Clone",
    forked: "Cloned",
    networkSection: "Builder.Community",
    networkTitle: "Top Creators",
    networkCount: "Builders Online",
    networkAction: "Message",
    networkMetric1: "Apps",
    networkMetric2: "Install Rate",
    identityMetric1Label: "Total App Installs",
    identityMetric1Value: "12.4k",
    identityMetric1Icon: "⤓",
    identityMetric2Label: "Apps Published",
    identityMetric2Value: "4",
    identityMetric3Label: "Revenue Share",
    identityMetric3Value: "0.85",
    identityMetric3Icon: "$",
    identityAction: "Publish New App",
    identityActionDesc: "Launch your orchestrator to the global community",
    initSection: "Builder.Publish",
    initHeading: "Publish App",
    initBroadcast: "Publish to Network",
    workbench: "Studio",
    workbenchUnauthorized: "Access to the Studio requires a registered account. Sign in to start building and publishing your apps.",
    workbenchUnauthorizedHeading: "Account Required",
    toasts: {
      unauthorized: "Please sign in to continue.",
      identityInitialized: "Welcome back!",
      broadcastSuccess: "Published successfully!",
      broadcastError: "Please sign in to publish.",
      networkPing: "Message sent to {name}",
      networkPingAll: "Sending messages to all creators...",
      workbenchSave: "App saved to your Studio.",
      workbenchIntegrate: "Starting integration...",
      auditComplete: "Optimization review complete for {name}",
      logout: "Signed out successfully.",
      loadingState: "Loading Dashboard...",
      errorBoundary: "Something went wrong.",
      errorRetry: "Try Again",
      postDetail: "App Details // {id}",
      themeInverted: "Theme updated.",
    },
  },
  guest: {
    home: "Explore",
    consoleTitle: "Explore Craftly Internet",
    consoleSearch: "Search by need (e.g., 'minimal portfolio')...",
    audit: "Rate",
    fork: "Save",
    forked: "Saved",
    networkSection: "Explore.People",
    networkTitle: "Global Community",
    networkCount: "People Exploring",
    networkAction: "Connect",
    networkMetric1: "Posts",
    networkMetric2: "Impact",
    identityMetric1Label: "Discovery Points",
    identityMetric1Value: "450",
    identityMetric1Icon: "☼",
    identityMetric2Label: "Nodes Saved",
    identityMetric2Value: "28",
    identityMetric3Label: "Contributions",
    identityMetric3Value: "12",
    identityMetric3Icon: "◈",
    identityAction: "Join a Network",
    identityActionDesc: "Connect with other digital orchestrators",
    initSection: "Get Started",
    initHeading: "Share Something",
    initBroadcast: "Post to Community",
    workbench: "Bookmarks",
    workbenchUnauthorized: "This area is for members. Create an account to save your favorite nodes and join the community.",
    workbenchUnauthorizedHeading: "Welcome, Guest",
    toasts: {
      unauthorized: "Sign in to access this feature.",
      identityInitialized: "Welcome to Craftly!",
      broadcastSuccess: "Posted to the community!",
      broadcastError: "Please sign in to post.",
      networkPing: "Connection request sent to {name}",
      networkPingAll: "Connecting with the community...",
      workbenchSave: "Saved to your Bookmarks.",
      workbenchIntegrate: "Opening saved item...",
      auditComplete: "Your rating has been saved for {name}",
      logout: "See you next time!",
      loadingState: "Loading...",
      errorBoundary: "Something went wrong.",
      errorRetry: "Try Again",
      postDetail: "Details // {id}",
      themeInverted: "Theme changed.",
    },
  },
} as const satisfies Record<UserRole, Record<string, string | Record<string, string>>>;

export function getRoleCopy(role: UserRole) {
  return roleCopy[role];
}
