import { UserRole } from '@/types';

export const roleCopy = {
  engineer: {
    // Console (Home)
    home: "Console",
    consoleTitle: "The Orchestrator's Console",
    consoleSearch: "type:project tags:auth metrics.forks>100",
    audit: "Audit",
    fork: "Fork",
    forked: "Forked",
    streamLive: "Stream.LIVE",
    streamSignal: "SIGNAL",
    nodeCount: "{n} Nodes",
    noResults: "0 Nodes Match Query",
    leadLabel: "LEAD ORCHESTRATOR",
    caseStudyHead: "01 // Architectural Case Study",
    logicHead: "02 // Logic Extraction",
    // Network
    networkSection: "System.Network",
    networkTitle: "Global Nodes",
    networkCount: "Active Orchestrators",
    networkAction: "Ping Node",
    networkMetric1: "Broadcasts",
    networkMetric2: "Fork Rate",
    networkIdLabel: "ID // {id}",
    networkSpecLabel: "Aura // Specialty",
    // Identity
    identitySubtitle: "System.Identity // Orchestrator Profile",
    identityMetric1Label: "Global Fork Rate",
    identityMetric1Value: "842",
    identityMetric1Icon: "⑂",
    identityMetric2Label: "Nodes Broadcasted",
    identityMetric2Value: "12",
    identityMetric3Label: "Peer Audits",
    identityMetric3Value: "56",
    identityMetric3Icon: "[A]",
    identityAction: "Initialize New Node",
    identityActionDesc: "Broadcast architectural logic to the network",
    switchMode: "Switch Operational Mode",
    // Init
    initSection: "System.Execute",
    initHeading: "Initialize Node",
    initBroadcast: "Broadcast to Console",
    accessDenied: "Access Denied",
    broadcastCreator: "USER.NODE_001",
    broadcastProjectTag: "System Node Init",
    broadcastProblem: "Initialization of new node architecture.",
    broadcastImpact: "System expanded.",
    broadcastLogic: "Node initialized via Console",
    nodeTypeLabel: "Node Type",
    projectSubtitle: "Architectural Case Study",
    experienceSubtitle: "Developer Log / Reflection",
    contentLabel: "Data Stream (Content)",
    broadcasting: "Broadcasting...",
    // Workbench
    workbench: "Workbench",
    workbenchUnauthorized: "The private sector is restricted to registered Orchestrators. You must initialize an identity to establish a Workbench and fork logic from the network.",
    workbenchUnauthorizedHeading: "[SYSTEM ERROR] UNREGISTERED NODE",
    developerLog: "Developer Log",
    inspectAction: "Inspect / Integrate",
    blueprintTitle: "Blueprint Archive",
    forkedCount: "{n} Forked Nodes",
    emptyWorkbench: "No Nodes in local memory",
    emptyWorkbenchDesc: "The Workbench is empty. Search the network and fork architectural logic to begin your local session.",
    returnLink: "Return to Console",
    forkNotes: "Auto-forked from network.",
    // Broadcast Modal
    experienceLabel: "Experience Log",
    experiencePlaceholder: "Document your architectural decisions or system reflections...",
    tagExamples: "architecture, philosophy, refactoring",
    toasts: {
      unauthorized: "[SYSTEM ERROR] UNAUTHORIZED. INITIALIZE IDENTITY.",
      identityInitialized: "[SYSTEM] IDENTITY INITIALIZED",
      broadcastSuccess: "[CONSOLE] NODE SUCCESSFULLY BROADCASTED",
      broadcastError: "[ERROR] UNAUTHORIZED. CANNOT BROADCAST.",
      networkPing: "[NETWORK] NODE PINGED: {name}",
      networkPingAll: "[NETWORK] PINGING ALL ACTIVE NODES...",
      workbenchSave: "[WORKBENCH] NODE FORKED AND SAVED",
      workbenchIntegrate: "[WORKBENCH] INITIATING INTEGRATION PROTOCOL",
      auditComplete: "[SYSTEM] AUDIT COMPLETE FOR NODE {name}",
      logout: "[SYSTEM] CONNECTION TERMINATED",
      loadingState: "Initializing Console...",
      errorBoundary: "[SYSTEM ERROR] RUNTIME FAULT",
      errorRetry: "Retry Connection",
      errorHeading: "Runtime Fault",
      errorDescription: "An unexpected error occurred in the system. The engineering team has been alerted.",
      postDetail: "Developer Log // {id}",
      themeInverted: "[SYSTEM] THEME INVERTED",
    },
  },
  builder: {
    home: "Dashboard",
    consoleTitle: "The Builder's Dashboard",
    consoleSearch: "Search apps, categories, or metrics...",
    audit: "Optimize",
    fork: "Clone",
    forked: "Cloned",
    streamLive: "Latest",
    streamSignal: "Trending",
    nodeCount: "{n} Apps",
    noResults: "No apps found",
    leadLabel: "FEATURED CREATOR",
    caseStudyHead: "01 // Case Study",
    logicHead: "02 // How It's Built",
    networkSection: "Builder.Community",
    networkTitle: "Top Creators",
    networkCount: "Builders Online",
    networkAction: "Message",
    networkMetric1: "Apps",
    networkMetric2: "Install Rate",
    networkIdLabel: "@",
    networkSpecLabel: "Specialty",
    identitySubtitle: "Account Settings",
    identityMetric1Label: "Total App Installs",
    identityMetric1Value: "12.4k",
    identityMetric1Icon: "⤓",
    identityMetric2Label: "Apps Published",
    identityMetric2Value: "4",
    identityMetric3Label: "Revenue Share",
    identityMetric3Value: "0.85",
    identityMetric3Icon: "$",
    identityAction: "Publish New App",
    identityActionDesc: "Launch your app to the community",
    switchMode: "Switch Account Type",
    initSection: "Builder.Publish",
    initHeading: "Publish App",
    initBroadcast: "Publish to Network",
    accessDenied: "Sign In Required",
    broadcastCreator: "You",
    broadcastProjectTag: "New App",
    broadcastProblem: "Creating a new application.",
    broadcastImpact: "App published to network.",
    broadcastLogic: "App created successfully.",
    nodeTypeLabel: "Post Type",
    projectSubtitle: "App Details",
    experienceSubtitle: "Notes & Updates",
    contentLabel: "Description",
    broadcasting: "Publishing...",
    workbench: "Studio",
    workbenchUnauthorized: "Access to the Studio requires a registered account. Sign in to start building and publishing your apps.",
    workbenchUnauthorizedHeading: "Account Required",
    developerLog: "Notes",
    inspectAction: "Review & Test",
    blueprintTitle: "My Studio",
    forkedCount: "{n} Cloned Apps",
    emptyWorkbench: "Your Studio is empty",
    emptyWorkbenchDesc: "Start building or clone existing apps to see them here.",
    returnLink: "Back to Dashboard",
    forkNotes: "Cloned from community.",
    experienceLabel: "Quick Update",
    experiencePlaceholder: "Share a product update or insight with the community...",
    tagExamples: "product-update, release, feature",
    toasts: {
      unauthorized: "Please sign in to continue.",
      identityInitialized: "Welcome back!",
      broadcastSuccess: "Published successfully!",
      broadcastError: "Please sign in to publish.",
      networkPing: "Message sent to {name}",
      networkPingAll: "Sending messages to all creators...",
      workbenchSave: "App saved to your Studio.",
      workbenchIntegrate: "Starting integration...",
      auditComplete: "Optimization review complete for {name}",
      logout: "Signed out successfully.",
      loadingState: "Loading Dashboard...",
      errorBoundary: "Something went wrong.",
      errorRetry: "Try Again",
      errorHeading: "Something Went Wrong",
      errorDescription: "An unexpected error occurred. Please try again or contact support.",
      postDetail: "App Details // {id}",
      themeInverted: "Theme updated.",
    },
  },
  guest: {
    home: "Explore",
    consoleTitle: "Explore Craftly Internet",
    consoleSearch: "Search by need (e.g., 'minimal portfolio')...",
    audit: "Rate",
    fork: "Save",
    forked: "Saved",
    streamLive: "Recent",
    streamSignal: "Popular",
    nodeCount: "{n} Posts",
    noResults: "No results",
    leadLabel: "FEATURED",
    caseStudyHead: "01 // How It Works",
    logicHead: "02 // How It Works",
    networkSection: "Explore.People",
    networkTitle: "Global Community",
    networkCount: "People Exploring",
    networkAction: "Connect",
    networkMetric1: "Posts",
    networkMetric2: "Impact",
    networkIdLabel: "",
    networkSpecLabel: "About",
    identitySubtitle: "Your Profile",
    identityMetric1Label: "Discovery Points",
    identityMetric1Value: "450",
    identityMetric1Icon: "☼",
    identityMetric2Label: "Posts Saved",
    identityMetric2Value: "28",
    identityMetric3Label: "Contributions",
    identityMetric3Value: "12",
    identityMetric3Icon: "◈",
    identityAction: "Join a Network",
    identityActionDesc: "Connect with others in the community",
    switchMode: "Change View",
    initSection: "Get Started",
    initHeading: "Share Something",
    initBroadcast: "Post to Community",
    accessDenied: "Sign In Required",
    broadcastCreator: "You",
    broadcastProjectTag: "New Post",
    broadcastProblem: "Sharing something new.",
    broadcastImpact: "Post shared with community.",
    broadcastLogic: "Post created successfully.",
    nodeTypeLabel: "Post Type",
    projectSubtitle: "Project Details",
    experienceSubtitle: "Your Thoughts",
    contentLabel: "What's on your mind?",
    broadcasting: "Posting...",
    workbench: "Bookmarks",
    workbenchUnauthorized: "This area is for members. Create an account to save your favorite nodes and join the community.",
    workbenchUnauthorizedHeading: "Welcome, Guest",
    developerLog: "Notes",
    inspectAction: "View Details",
    blueprintTitle: "My Bookmarks",
    forkedCount: "{n} Saved Items",
    emptyWorkbench: "No bookmarks yet",
    emptyWorkbenchDesc: "Save posts you like to find them here later.",
    returnLink: "Back to Explore",
    forkNotes: "Saved from explore.",
    experienceLabel: "Your Story",
    experiencePlaceholder: "Share a thought or experience with the world...",
    tagExamples: "design, technology, ideas",
    toasts: {
      unauthorized: "Sign in to access this feature.",
      identityInitialized: "Welcome to Craftly!",
      broadcastSuccess: "Posted to the community!",
      broadcastError: "Please sign in to post.",
      networkPing: "Connection request sent to {name}",
      networkPingAll: "Connecting with the community...",
      workbenchSave: "Saved to your Bookmarks.",
      workbenchIntegrate: "Opening saved item...",
      auditComplete: "Your rating has been saved for {name}",
      logout: "See you next time!",
      loadingState: "Loading...",
      errorBoundary: "Something went wrong.",
      errorRetry: "Try Again",
      errorHeading: "Something Went Wrong",
      errorDescription: "Something broke. Please try refreshing the page or checking your connection.",
      postDetail: "Details // {id}",
      themeInverted: "Theme changed.",
    },
  },
} as const satisfies Record<UserRole, Record<string, string | Record<string, string>>>;

export function getRoleCopy(role: UserRole) {
  return roleCopy[role];
}
